### PR TITLE
Added main.py to help learners import modules

### PR DESCRIPTION
**Pull request by dancer-yuma**
# What I did

- 03-02 challenge is using `random` and `math` modules but learners don't know how to import modules. I added `main.py` so that learners can use them already.

### CODE REVIEW

**Review by xvarc-wp — APPROVED** [review]
@dancer-yuma in this case I think it could also be fine to give a more descriptive name to the python file e.g. rock_paper_scissors.py. 

I think your addition is a thoughtful addition but is there any specific reason you are sticking to main.py?

My only concern is that if that is the conventional naming system we use, learners will have a huge number of main.py files.

**Comment by dancer-yuma** [comment]
> @dancer-yuma in this case I think it could also be fine to give a more descriptive name to the python file e.g. rock_paper_scissors.py.
> 
> I think your addition is a thoughtful addition but is there any specific reason you are sticking to main.py?
> 
> My only concern is that if that is the conventional naming system we use, learners will have a huge number of main.py files.

@xvarc-wp 
Ahh sorry switching between C++ and Python is sometimes very confusing...
I will change the file name as you suggested!

**Comment by dancer-yuma** [comment]
@xvarc-wp 
Fixed it in [070287c](https://github.com/ms1-learner/python-01-en/pull/10/commits/070287ca663fb3db85050277577b39a162305ab2). Can you review again?

**Review by xvarc-wp — APPROVED** [review]
LGTM

To be clear, I think the inclusion of math and random is a good addition too. 

I think for later modules we don't always need to hold their hand so much but definitely for early modules it is good to do that.

Nice work.

**Pull request merged**
